In [1]:
import refinitiv.data as rd
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import yfinance as yf

In [29]:
rd.open_session()

In [ ]:
tickers = [
    "ASML.AS",
    "MC.PA",
    "SAN.PA",
    "AIR.PA",
    "SU.PA",
    "OR.PA",
    "BNP.PA",
    "RMS.PA",
    "DG.PA",
    "ADS.DE"
]

In [33]:
general_data = rd.get_data(
    universe=tickers,
    fields = [
        "TR.CompanyName",
        "TR.Sector",
        "TR.Industry",
    ])

RDError: Error code -1 | {"code":500,"message":"Network Error"} Requested universes: ['MANP.PA', 'CASHP.MC', 'DEA.N', 'KOS.N', 'EPC.N', 'CSR.N', 'CMP.N', 'NX.N', 'SAVEN.PA', 'ESRT.N', 'VIRI.PA', 'CBAV.MC', 'ALV.DE']. Requested fields: ['TR.COMPANYNAME', 'TR.SECTOR', 'TR.INDUSTRY']

In [28]:
general_data.head()

  Instrument                        Company Name
0    MANP.PA                       Manitou BF SA
1   CASHP.MC                    Prosegur Cash SA
2      DEA.N  Easterly Government Properties Inc
3      KOS.N                   Kosmos Energy Ltd
4      EPC.N           Edgewell Personal Care Co

In [4]:
end = datetime.today()
start = end - timedelta(days=365)

In [10]:
df_test = rd.get_history(
    universe=["ASML.AS"],
    fields=["TRDPRC_1"],
    start="2025-12-01",
    end="2025-12-31"
)
df_test.head()

ASML.AS     TRDPRC_1
Date
2025-12-02     939.1
2025-12-03     963.4
2025-12-04     957.3
2025-12-05     951.6
2025-12-08     963.2

In [27]:
all_data = []

for t in tickers:
    try:
        df = rd.get_history(
            universe=[t],
            fields=["TRDPRC_1"],
            start=start,
            end=end
        )
        df["Ticker"] = t
        all_data.append(df)

    except Exception as e:
        print(f"Fail: {t}", e)

final_df = pd.concat(all_data)
final_df

Fail: MANP.PA Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})
Fail: CASHP.MC Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})
Fail: DEA.N Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})
Fail: KOS.N Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})
Fail: EPC.N Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})
Fail: CSR.N Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})
Fail: CMP.N Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})
Fail: NX.N Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})
Fail: SAVEN.PA Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})
Fail: ESRT.N Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})
Fail: VIRI.PA Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})
Fail: CBAV.MC Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})
Fail: ALV.DE Error code -1 | No data to return, please check errors: ERROR: No successful response.
(500, {"code":500,"message":"Network Error"})

ValueError: No objects to concatenate

In [ ]:
data.to_excel("stock_prices.xlsx")

In [12]:
df_test = rd.get_history(
    universe=["ASML.AS"],
    fields=["TRDPRC_1"],
    start="2025-12-01",
    end="2025-12-31"
)
df_test.head()

ASML.AS     TRDPRC_1
Date
2025-12-02     939.1
2025-12-03     963.4
2025-12-04     957.3
2025-12-05     951.6
2025-12-08     963.2